version: "3.5"
services:
  admin_app_gateway:
    env_file:
      - .env
    build: .
    image: ien_backend_image:latest
    command: bash -c "python3 manage.py runserver 0.0.0.0:5600"
    ports:
      - "5600:5600"
    deploy:
      update_config:
        parallelism: 1
        max_failure_ratio: 0
        delay: 3s
        failure_action: rollback
      restart_policy:
        max_attempts: 3
        condition: on-failure
      replicas: 2
      placement:
        constraints: [node.role == manager]
    volumes:
      - .:/src
      - /opt/logs:/opt/logs
    networks:
      - ien_main_network
networks:
  ien_main_network:
    external: true