# Generated by Django 3.2.5 on 2021-08-22 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_manager', '0003_developmentstage_industry_intellectualproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_terms', models.BooleanField(default=False)),
                ('status', models.CharField(default='ONGOING', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'innovation',
            },
        ),
        migrations.CreateModel(
            name='InnovationSupportService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_support_services', to='innovation.innovation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_service', to='app_manager.supportservices')),
            ],
            options={
                'db_table': 'innovation_support_services',
            },
        ),
        migrations.CreateModel(
            name='InnovationSocialLinks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innovation_video', models.CharField(max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_social_links', to='innovation.innovation')),
            ],
            options={
                'db_table': 'innovation_social_links',
            },
        ),
        migrations.CreateModel(
            name='InnovationInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innovation_brief', models.TextField()),
                ('problem_statement', models.TextField()),
                ('background_research', models.TextField()),
                ('target_customers', models.TextField()),
                ('value_proposition', models.TextField()),
                ('solution', models.TextField()),
                ('how_it_works', models.TextField()),
                ('impact', models.TextField()),
                ('competitors', models.TextField()),
                ('competitive_advantage', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_information', to='innovation.innovation')),
            ],
            options={
                'db_table': 'innovation_information',
            },
        ),
        migrations.CreateModel(
            name='InnovationDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innovation_name', models.CharField(max_length=100)),
                ('other_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('area_of_focus', models.CharField(max_length=100)),
                ('is_pitched_before', models.CharField(max_length=100)),
                ('has_won_awards', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.CharField(blank=True, max_length=100, null=True)),
                ('recognitions', models.CharField(max_length=100)),
                ('require_accreditation', models.CharField(blank=True, max_length=100, null=True)),
                ('accreditation_bodies', models.CharField(blank=True, max_length=100, null=True)),
                ('hub_affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('hub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('other_hub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('development_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_development_stage', to='app_manager.developmentstage')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_industry', to='app_manager.industry')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_industry', to='innovation.innovation')),
                ('intellectual_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_intellectual_property', to='app_manager.intellectualproperty')),
            ],
            options={
                'db_table': 'innovation_details',
            },
        ),
    ]
