# Generated by Django 3.2.5 on 2021-08-22 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0004_hubs'),
        ('innovation', '0002_innovationdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationdetails',
            name='intellectual_property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='innovation_intellectual_property', to='app_manager.intellectualproperty'),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='recognitions',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
