# Generated by Django 3.2.5 on 2021-08-23 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0004_hubs'),
        ('innovation', '0003_auto_20210823_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationdetails',
            name='intellectual_property',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innovation_intellectual_property', to='app_manager.intellectualproperty'),
        ),
    ]
