# Generated by Django 3.2.5 on 2021-08-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0004_alter_innovationdetails_intellectual_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationsociallinks',
            name='wesite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='status',
            field=models.CharField(default='ONGOING', max_length=255),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='accreditation_bodies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='area_of_focus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='awards',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='has_won_awards',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='hub_affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='hub_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='innovation_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='is_pitched_before',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='other_hub_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='other_industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='recognitions',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='innovationdetails',
            name='require_accreditation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationdocument',
            name='original_file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='innovationdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationsociallinks',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationsociallinks',
            name='innovation_video',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='innovationsociallinks',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationsociallinks',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='innovationsociallinks',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
