# Generated by Django 3.2.5 on 2021-08-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0005_auto_20210823_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovationsociallinks',
            old_name='wesite',
            new_name='website',
        ),
    ]
