# Generated by Django 3.2.5 on 2021-09-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0006_rename_wesite_innovationsociallinks_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationdetails',
            name='accreditation_bodies',
        ),
        migrations.RemoveField(
            model_name='innovationdetails',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='innovationdetails',
            name='recognitions',
        ),
        migrations.CreateModel(
            name='Recognitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='innovation.innovation')),
            ],
            options={
                'db_table': 'recognitions',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='innovation.innovation')),
            ],
            options={
                'db_table': 'awards',
            },
        ),
        migrations.CreateModel(
            name='AccreditationBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_bodies', to='innovation.innovation')),
            ],
            options={
                'db_table': 'accreditation_bodies',
            },
        ),
    ]
