# Generated by Django 3.2.5 on 2021-09-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0009_evaluation_impact_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='competitors_observation',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='competitors_score',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
