# Generated by Django 3.2.5 on 2021-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0009_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
