# Generated by Django 3.2.5 on 2021-09-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0010_alter_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_status',
            field=models.CharField(default='SUBMITTED', max_length=100),
        ),
    ]
