# Generated by Django 3.2.5 on 2021-09-24 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovation', '0013_group_groupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='innovation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='innovation.innovation'),
        ),
        migrations.CreateModel(
            name='InnovationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='innovation.innovation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'innovation_reviews',
            },
        ),
    ]
