# Generated by Django 3.2.5 on 2021-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0016_innovationmanagerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='innovation',
            name='stage',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
