# Generated by Django 3.2.5 on 2021-09-28 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovation', '0018_auto_20210928_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalInnovationManagerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fim_reviews', to='innovation.innovation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fim_review_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'final_innovation_manager_reviews',
            },
        ),
    ]
