# Generated by Django 3.2.5 on 2021-09-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0020_auto_20210929_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='stage',
            field=models.CharField(default='I', max_length=5),
        ),
    ]
