# Generated by Django 3.2.5 on 2022-01-12 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0021_alter_innovation_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('assignment_status', models.CharField(default='SUBMITTED', max_length=100)),
                ('response', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_response', to='innovation.assignment')),
            ],
            options={
                'db_table': 'assignment_response',
            },
        ),
    ]
