# Generated by Django 3.2.5 on 2022-02-09 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovation', '0022_assignmentresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_innovation', to='innovation.innovation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
