# Generated by Django 3.2.5 on 2022-02-09 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovation', '0023_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='receipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
