# Generated by Django 3.2.5 on 2022-02-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0024_notifications_receipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='receipient',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='innovation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_innovation', to='innovation.innovation'),
        ),
    ]
