# Generated by Django 3.2.5 on 2022-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0025_auto_20220210_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationreview',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
