# Generated by Django 3.2.5 on 2022-03-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0026_innovationreview_is_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationreview',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
