# Generated by Django 3.2.5 on 2022-03-15 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovation', '0027_innovationreview_is_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalEvaluatorsComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_reviews', to='innovation.innovation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'final_evaluators_comments',
            },
        ),
    ]
