# Generated by Django 3.2.5 on 2022-03-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0028_finalevaluatorscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalevaluatorscomment',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
