# Generated by Django 3.2.5 on 2022-03-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0029_finalevaluatorscomment_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
