# Generated by Django 3.2.5 on 2022-03-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0030_notifications_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='action',
            new_name='subject',
        ),
    ]
