# Generated by Django 3.2.5 on 2022-03-22 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0031_rename_action_notifications_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFinalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_pending_final_report', to='innovation.innovation')),
            ],
            options={
                'db_table': 'pending_final_report',
            },
        ),
    ]
