# Generated by Django 3.2.5 on 2022-04-04 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0032_pendingfinalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInnovationSupportService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otehr_innovation_support_services', to='innovation.innovation')),
            ],
            options={
                'db_table': 'other_innovation_support_services',
            },
        ),
    ]
