# Generated by Django 3.2.5 on 2021-08-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportservices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
