# Generated by Django 3.2.5 on 2022-06-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidateposition_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateposition',
            name='application_status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
