# Generated by Django 3.2.5 on 2022-07-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0005_auto_20220630_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterTokens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voter_tokens',
            },
        ),
        migrations.CreateModel(
            name='IsVoter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_voter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'is_voter',
            },
        ),
    ]
