# Generated by Django 3.2.5 on 2022-07-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='education',
            name='study_summary',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='county',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='state',
        ),
    ]
