# Generated by Django 3.2.5 on 2021-07-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_auto_20210730_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcodes',
            old_name='activity',
            new_name='otp',
        ),
    ]
