# Generated by Django 3.2.5 on 2021-08-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20210807_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='about',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
