# Generated by Django 3.2.5 on 2021-08-07 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0008_auto_20210807_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='age',
            new_name='age_group',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
