# Generated by Django 3.2.5 on 2021-08-08 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0009_auto_20210807_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='id_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
