# Generated by Django 3.2.5 on 2021-08-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0010_userinfo_id_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
    ]
