# Generated by Django 3.2.5 on 2021-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0011_alter_document_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hear_about_us_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
