# Generated by Django 3.2.5 on 2021-09-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0014_association_certification_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardian',
            },
        ),
    ]
