# Generated by Django 3.2.5 on 2021-09-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0015_auto_20210920_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
