# Generated by Django 3.2.5 on 2022-01-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0017_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
