# Generated by Django 3.2.5 on 2022-01-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0019_association_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
