# Generated by Django 3.2.5 on 2022-02-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0020_alter_association_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
